safe:        true
#auto:        false
#server:      false
port: 4000
baseurl:     /

exclude: [README.md, CONTRIBUTING.md]

source:      .
destination: ./_site
plugins_dir: ./_plugins

future:      true
lsi:         false
highlighter: false
markdown:    kramdown
permalink:   date
